name: NodeJS App

on:
  # run it on push to the default repository branch
  push:
    branches: [master]
  # run it during pull request
  pull_request:
    branches: [master]

jobs:
   build:
         runs-on: ubuntu-latest
         steps:
         - name: Push & Build
         - uses: actions/checkout@v2
           run: |
              echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u "kayvan45622" --password-stdin
              docker image build -t kayvan45622/xaudanewapp:v1 .
              docker push kayvan45622/xaudanewapp:v1

