on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: xaudaapp.azurecr.io
        username: ${{ secrets.acr_xaudaapp_username }}
        password: ${{ secrets.acr_xaudaapp_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t xaudaapp.azurecr.io/newxaudaapp:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push xaudaapp.azurecr.io/newxaudaapp:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_newxaudaapp_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep newxaudaappa145 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace newxaudaappa145`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: newxaudaappa145
        container-registry-url: xaudaapp.azurecr.io
        container-registry-username: ${{ secrets.acr_xaudaapp_username }}
        container-registry-password: ${{ secrets.acr_xaudaapp_password }}
        secret-name: newxaudaappdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: newxaudaappa145
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          xaudaapp.azurecr.io/newxaudaapp:${{ github.sha }}
        imagepullsecrets: |
          newxaudaappdockerauth
