name: Kevin Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
           docker build . --file Dockerfile --tag my-image-name:$(date +%s)
           echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u "kayvan45622" --password-stdin
           docker image build -t kayvan45622/xaudanewapp:v1 .
           docker push kayvan45622/xaudanewapp:v1
